# kotoba default configuration file

llm:
  model_name: "rinna/japanese-gpt-neox-3.6b"  # Lightweight model specialized for Japanese
  device: "auto"
  max_length: 512
  temperature: 0.7
  top_p: 0.9

playwright:
  browser: "chromium"
  headless: true
  timeout: 30000
  viewport:
    width: 1280
    height: 720

test:
  base_url: ""
  screenshot_on_failure: true
  output_dir: "outputs"
  retry_count: 3

log_level: "INFO"